"""
skills_data13.py — Nuxt.js / Vue SPA 전용 취약점 스캔 스킬 DB
bingo v2.3.12

9 new skills:
  1. nuxt-sourcemap-leak      — /_nuxt/*.js.map 소스맵 노출 및 원본 코드 복원
  2. nuxt-payload-dump        — /_payload.json 경로 퍼징 (데이터 탈취)
  3. nuxt-env-exposure        — .env / nuxt.config.* 파일 노출
  4. nuxt-devtools-detect     — Nuxt DevTools 노출 여부
  5. nuxt-api-route-extract   — 소스맵에서 server/api/ 경로 자동 추출
  6. nuxt-aws-ssrf            — AWS App Runner 메타데이터 SSRF
  7. nuxt-build-artifact      — .output / .nuxt 빌드 아티팩트 노출
  8. nuxt-js-chunk-secrets    — JS 청크 파일 하드코딩 시크릿 스캔
  9. nuxt-full-pipeline       — Nuxt.js 전체 공격 파이프라인 자동화
"""
from __future__ import annotations

SKILLS_DB_13: dict[str, dict] = {

    # ── 1. Source Map Leak ─────────────────────────────────────────────────────
    "nuxt-sourcemap-leak": {
        "id":          "nuxt-sourcemap-leak",
        "name":        "Nuxt.js Source Map Leak",
        "name_ko":     "Nuxt.js 소스맵 노출",
        "name_zh":     "Nuxt.js源码映射泄露",
        "description": (
            "Discover exposed JavaScript source maps (*.js.map) in Nuxt.js applications. "
            "Source maps contain the original unminified source code, revealing API endpoints, "
            "hardcoded secrets, authentication logic, and internal business rules. "
            "Enumerate /_nuxt/ directory for .map files, then reconstruct source tree."
        ),
        "description_ko": (
            "Nuxt.js 앱에서 노출된 JS 소스맵(*.js.map)을 탐지한다. "
            "소스맵에는 원본 비압축 소스코드가 포함되어 있어 API 엔드포인트, "
            "하드코딩 시크릿, 인증 로직, 내부 비즈니스 규칙이 노출된다. "
            "/_nuxt/ 디렉터리에서 .map 파일을 열거하고 원본 소스 트리를 복원한다."
        ),
        "description_zh": (
            "发现Nuxt.js应用中暴露的JavaScript源码映射文件(*.js.map)。"
            "源码映射包含原始未压缩的源代码，可揭示API端点、硬编码密钥、认证逻辑。"
            "枚举/_nuxt/目录中的.map文件并重建源码树。"
        ),
        "tags": ["nuxt", "vue", "sourcemap", "recon", "spa", "javascript", "secret", "api"],
        "module": "nuxt",
        "phase": "recon",
        "severity": "high",
        "auto_trigger": ["nuxt", "vue", "spa", "sourcemap", "js.map", "/_nuxt/"],
    },

    # ── 2. _payload.json Dump ──────────────────────────────────────────────────
    "nuxt-payload-dump": {
        "id":          "nuxt-payload-dump",
        "name":        "Nuxt.js _payload.json Dump",
        "name_ko":     "Nuxt.js 페이로드 JSON 탈취",
        "name_zh":     "Nuxt.js载荷JSON转储",
        "description": (
            "Enumerate and download _payload.json files generated by Nuxt.js static generation (SSG). "
            "Each page in a Nuxt SSG build has a corresponding _payload.json containing the page's "
            "data-fetching results — potentially including user data, tokens, DB records, or admin info."
        ),
        "description_ko": (
            "Nuxt.js 정적 생성(SSG)이 만드는 _payload.json 파일을 열거·다운로드한다. "
            "SSG 빌드에서 각 페이지는 데이터 패칭 결과를 담은 _payload.json을 가진다 — "
            "사용자 데이터, 토큰, DB 레코드, 어드민 정보가 포함될 수 있다."
        ),
        "description_zh": (
            "枚举并下载Nuxt.js静态生成(SSG)生成的_payload.json文件。"
            "SSG构建中每个页面都有对应的_payload.json，包含数据获取结果，"
            "可能包含用户数据、令牌、数据库记录或管理员信息。"
        ),
        "tags": ["nuxt", "ssg", "payload", "data-leak", "recon", "spa"],
        "module": "nuxt",
        "phase": "recon",
        "severity": "high",
        "auto_trigger": ["_payload.json", "nuxt", "ssg", "static generation"],
    },

    # ── 3. .env / Config Exposure ──────────────────────────────────────────────
    "nuxt-env-exposure": {
        "id":          "nuxt-env-exposure",
        "name":        "Nuxt.js .env / Config File Exposure",
        "name_ko":     "Nuxt.js 환경변수 파일 노출",
        "name_zh":     "Nuxt.js环境变量文件暴露",
        "description": (
            "Check for exposed .env, nuxt.config.js/ts, and other configuration files "
            "in Nuxt.js deployments that may contain database credentials, API keys, "
            "JWT secrets, and cloud provider tokens."
        ),
        "description_ko": (
            "Nuxt.js 배포에서 노출된 .env, nuxt.config.js/ts 및 기타 설정 파일을 확인한다. "
            "DB 자격증명, API 키, JWT 시크릿, 클라우드 토큰이 포함될 수 있다."
        ),
        "description_zh": (
            "检查Nuxt.js部署中暴露的.env、nuxt.config.js/ts和其他配置文件。"
            "可能包含数据库凭据、API密钥、JWT密钥和云提供商令牌。"
        ),
        "tags": ["nuxt", "env", "config", "secret", "recon"],
        "module": "nuxt",
        "phase": "recon",
        "severity": "critical",
        "auto_trigger": [".env", "nuxt.config", "environment variable"],
    },

    # ── 4. Nuxt DevTools Detect ────────────────────────────────────────────────
    "nuxt-devtools-detect": {
        "id":          "nuxt-devtools-detect",
        "name":        "Nuxt DevTools Exposure Detection",
        "name_ko":     "Nuxt DevTools 노출 탐지",
        "name_zh":     "Nuxt DevTools暴露检测",
        "description": (
            "Detect accidentally exposed Nuxt DevTools in production environments. "
            "Nuxt DevTools provides access to component inspector, route list, state viewer, "
            "and server RPC endpoints — a critical exposure if left enabled in production."
        ),
        "description_ko": (
            "운영 환경에 실수로 노출된 Nuxt DevTools를 탐지한다. "
            "DevTools는 컴포넌트 인스펙터, 라우트 목록, 상태 뷰어, "
            "서버 RPC 엔드포인트 접근을 제공 — 운영에서 활성화되면 심각한 노출이다."
        ),
        "description_zh": (
            "检测生产环境中意外暴露的Nuxt DevTools。"
            "DevTools提供组件检查器、路由列表、状态查看器和服务器RPC端点访问，"
            "若在生产环境启用则是严重暴露。"
        ),
        "tags": ["nuxt", "devtools", "debug", "recon", "misconfiguration"],
        "module": "nuxt",
        "phase": "recon",
        "severity": "high",
        "auto_trigger": ["devtools", "nuxt debug", "nuxt dev"],
    },

    # ── 5. API Route Extraction from Source Maps ───────────────────────────────
    "nuxt-api-route-extract": {
        "id":          "nuxt-api-route-extract",
        "name":        "Nuxt.js API Route Extraction",
        "name_ko":     "Nuxt.js API 라우트 추출",
        "name_zh":     "Nuxt.js API路由提取",
        "description": (
            "Extract server-side API routes from Nuxt.js source maps and JS chunks. "
            "Nuxt server/api/ directory routes are compiled into JS — source map analysis "
            "can reveal hidden API endpoints that are not publicly documented."
        ),
        "description_ko": (
            "Nuxt.js 소스맵과 JS 청크에서 서버사이드 API 라우트를 추출한다. "
            "Nuxt server/api/ 디렉터리 라우트는 JS로 컴파일되며 — "
            "소스맵 분석으로 공개되지 않은 숨겨진 API 엔드포인트를 발견할 수 있다."
        ),
        "description_zh": (
            "从Nuxt.js源码映射和JS块中提取服务端API路由。"
            "Nuxt server/api/目录路由被编译进JS中，"
            "源码映射分析可以发现未公开的隐藏API端点。"
        ),
        "tags": ["nuxt", "api", "route", "recon", "endpoint-discovery"],
        "module": "nuxt",
        "phase": "recon",
        "severity": "medium",
        "auto_trigger": ["nuxt api route", "server/api", "nuxt endpoint"],
    },

    # ── 6. AWS App Runner SSRF ─────────────────────────────────────────────────
    "nuxt-aws-ssrf": {
        "id":          "nuxt-aws-ssrf",
        "name":        "AWS App Runner Metadata SSRF",
        "name_ko":     "AWS App Runner 메타데이터 SSRF",
        "name_zh":     "AWS App Runner元数据SSRF",
        "description": (
            "Test for Server-Side Request Forgery (SSRF) to AWS metadata endpoints in "
            "Nuxt.js apps deployed on AWS App Runner. Successful exploitation can retrieve "
            "IAM credentials, environment variables, and cloud configuration data."
        ),
        "description_ko": (
            "AWS App Runner에 배포된 Nuxt.js 앱에서 AWS 메타데이터 엔드포인트로의 "
            "SSRF를 테스트한다. 성공 시 IAM 자격증명, 환경변수, 클라우드 설정 데이터를 탈취할 수 있다."
        ),
        "description_zh": (
            "测试部署在AWS App Runner上的Nuxt.js应用中指向AWS元数据端点的SSRF。"
            "成功利用可获取IAM凭据、环境变量和云配置数据。"
        ),
        "tags": ["nuxt", "aws", "ssrf", "cloud", "metadata", "iam", "apprunner"],
        "module": "nuxt",
        "phase": "exploit",
        "severity": "critical",
        "auto_trigger": ["aws apprunner", "awsapprunner", "aws ssrf", "metadata"],
    },

    # ── 7. Build Artifact Exposure ─────────────────────────────────────────────
    "nuxt-build-artifact": {
        "id":          "nuxt-build-artifact",
        "name":        "Nuxt.js Build Artifact Exposure",
        "name_ko":     "Nuxt.js 빌드 아티팩트 노출",
        "name_zh":     "Nuxt.js构建产物暴露",
        "description": (
            "Detect exposed Nuxt.js build artifacts including .output/, .nuxt/, "
            "dist/, and node_modules/ directories that may contain source code, "
            "configuration files, and sensitive build-time data."
        ),
        "description_ko": (
            "Nuxt.js 빌드 아티팩트 노출을 탐지한다: .output/, .nuxt/, "
            "dist/, node_modules/ 디렉터리에 소스코드, 설정 파일, 빌드 시점 민감 데이터가 포함될 수 있다."
        ),
        "description_zh": (
            "检测暴露的Nuxt.js构建产物，包括.output/、.nuxt/、dist/和node_modules/目录，"
            "可能包含源代码、配置文件和敏感的构建时数据。"
        ),
        "tags": ["nuxt", "build", "artifact", "disclosure", "recon"],
        "module": "nuxt",
        "phase": "recon",
        "severity": "high",
        "auto_trigger": ["nuxt build", ".output", ".nuxt directory", "build artifact"],
    },

    # ── 8. JS Chunk Secret Scanner ─────────────────────────────────────────────
    "nuxt-js-chunk-secrets": {
        "id":          "nuxt-js-chunk-secrets",
        "name":        "Nuxt.js JS Chunk Hardcoded Secret Scanner",
        "name_ko":     "Nuxt.js JS 청크 하드코딩 시크릿 스캔",
        "name_zh":     "Nuxt.js JS块硬编码密钥扫描",
        "description": (
            "Scan all Nuxt.js JavaScript chunk files for hardcoded secrets, "
            "API keys, tokens, and credentials that developers accidentally embedded "
            "in client-side code."
        ),
        "description_ko": (
            "Nuxt.js JS 청크 파일 전체를 하드코딩 시크릿, API 키, 토큰, "
            "자격증명에 대해 스캔한다 — 개발자가 클라이언트 코드에 실수로 포함한 것들."
        ),
        "description_zh": (
            "扫描所有Nuxt.js JavaScript块文件中的硬编码密钥、API密钥、令牌和凭据，"
            "这些是开发者意外嵌入客户端代码中的敏感信息。"
        ),
        "tags": ["nuxt", "javascript", "secret", "hardcoded", "api-key", "recon"],
        "module": "nuxt",
        "phase": "recon",
        "severity": "critical",
        "auto_trigger": ["js chunk", "hardcoded secret", "nuxt secret scan"],
    },

    # ── 9. Full Pipeline ───────────────────────────────────────────────────────
    "nuxt-full-pipeline": {
        "id":          "nuxt-full-pipeline",
        "name":        "Nuxt.js Full Attack Pipeline",
        "name_ko":     "Nuxt.js 전체 공격 파이프라인",
        "name_zh":     "Nuxt.js完整攻击流水线",
        "description": (
            "Automated full-scope Nuxt.js security assessment pipeline. "
            "Sequentially executes: source map discovery → JS chunk secret scan → "
            "_payload.json enumeration → .env exposure check → DevTools detection → "
            "API route extraction → AWS SSRF test. "
            "AI auto-selects this skill when target is identified as Nuxt.js/Vue SPA."
        ),
        "description_ko": (
            "Nuxt.js 전체 범위 자동 보안 평가 파이프라인. "
            "소스맵 발견 → JS 청크 시크릿 스캔 → _payload.json 열거 → "
            ".env 노출 확인 → DevTools 탐지 → API 라우트 추출 → AWS SSRF 테스트를 순차 실행. "
            "AI는 타겟이 Nuxt.js/Vue SPA로 식별될 때 자동으로 이 스킬을 선택한다."
        ),
        "description_zh": (
            "Nuxt.js全范围自动安全评估流水线。"
            "顺序执行：源码映射发现→JS块密钥扫描→_payload.json枚举→"
            ".env暴露检查→DevTools检测→API路由提取→AWS SSRF测试。"
            "当目标被识别为Nuxt.js/Vue SPA时AI自动选择此技能。"
        ),
        "tags": ["nuxt", "vue", "spa", "pipeline", "full-scan", "auto", "aws"],
        "module": "nuxt",
        "phase": "full",
        "severity": "critical",
        "auto_trigger": [
            "nuxt", "vue", "spa", "awsapprunner", "nuxtjs",
            "nuxt.js", "_nuxt/", "/_nuxt", "nuxt app",
        ],
    },
}

# ── Index builders ────────────────────────────────────────────────────────────

MODULE_INDEX_13: dict[str, list[str]] = {}
TAG_INDEX_13:    dict[str, list[str]] = {}

for _sid, _skill in SKILLS_DB_13.items():
    _mod = _skill.get("module", "")
    if _mod:
        MODULE_INDEX_13.setdefault(_mod, []).append(_sid)
    for _tag in _skill.get("tags", []):
        TAG_INDEX_13.setdefault(_tag.lower(), []).append(_sid)
